feat: Added a 'More from publisher' section to the Marketplace's 'App Details' view
APISuite/apisuite-marketplace-extension-ui pull request #32
Opened 2021-06-30 08:43 UTC by pedroCloudoki

2021-06-30 09:23 UTC, s1moe2 requested changes

2021-06-30 10:39 UTC, s1moe2 submitted a review, later dismissed

2021-06-30 10:39 UTC, s1moe2 commented on lib/pages/AppDetails/AppDetails.tsx
> +              app.shortDescription.length > 0
This condition is used in 2 other places. Needs to be extracted and refactored (and possibly changed to non-ternary syntax).

2021-07-02 07:56 UTC, a31859 requested changes

2021-07-02 07:56 UTC, a31859 commented on lib/pages/Marketplace/Marketplace.tsx
> +        return appDetailsMapping(app)
Move to saga like it was done for the publisher.

2021-07-02 07:56 UTC, a31859 commented on lib/pages/Marketplace/Marketplace.tsx
> +        return appDetailsMapping(filteredApp)
Move to saga like it was done for the publisher.

2021-07-02 10:18 UTC, a31859 approved these changes

2021-07-02 12:40 UTC, merged

2021-07-02 12:45 UTC, apisuite-machine-user commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/APISuite/apisuite-marketplace-extension-ui/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: