fix: Fixed some design inconsistencies on Marketplace-related stuff
APISuite/apisuite-marketplace-extension-ui pull request #35
Opened 2021-07-08 17:10 UTC by pedroCloudoki

2021-07-08 17:55 UTC, a31859 requested changes
Also use named exports. 
Instead of `export default MyComponent2` use `export const MyComponent2 = () => {}`

2021-07-08 17:55 UTC, a31859 commented on lib/components/CTACard/CTACard.tsx
> +                padding: '24px 0px 24px 40px',
use theme spacing

2021-07-08 17:55 UTC, a31859 commented on lib/pages/PublisherDetails/PublisherDetails.tsx
> +  const theme = useTheme()
```suggestion
  const { palette, spacing } = useTheme()
```

2021-07-08 17:55 UTC, a31859 commented on lib/components/CTACard/CTACard.tsx
> +            <CardActions style={{ paddingRight: 40 }}>
```suggestion
            <CardActions style={{ paddingRight: spacing(5) }}>
```
use theme spacing

2021-07-09 06:39 UTC, mstrk approved these changes

2021-07-09 06:41 UTC, merged

2021-07-09 06:43 UTC, apisuite-machine-user commented
:tada: This PR is included in version 1.4.1 :tada:

The release is available on [GitHub release](https://github.com/APISuite/apisuite-marketplace-extension-ui/releases/tag/v1.4.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: